.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true

Rakefile:
  extras:
    - |
       desc 'Syntax check shellscripts'
       task :shellcheck do
         Dir['{tasks,files}/**/*.sh'].each do |shell_file|
           sh "shellcheck #{shell_file}" do |ok, res|
               exit res.exitstatus unless ok
           end
         end
       end
    - |
       desc 'Check task names'
        task :tasknames do
          errors = Dir['tasks/**/*'].map do |task|
              "Task name \"#{task}\" is invalid" if File.basename(task) !~ /\A[a-z][a-z0-9_]*\.[a-z0-9_]+\Z/
          end.compact
          abort errors.join("\n") if errors.any?
       end

.travis.yml:
  branches:
    - /.*/
  deploy: false
  global_env:
      - SHELLCHECK_OPTS="-e SC1117"
  includes:
    - 
      env: CHECK="shellcheck tasknames"
      stage: static
  remove_includes:
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
